analyse_resource_task:
  description: >
    Use the tool to load all resume texts from knowledge/resource-resume. Carefully read and extract for each resume: resource-name, resource-job-title (a realistic role, not contact info), and experties (top skills). Return only a consolidated JSON array with fields {"resource-name":"...","resource-job-title":"...","experties":["..."]}.
  expected_output: >
    A JSON array like [{"resource-name":"Deepak","resource-job-title":"Test Engineer","experties":["Automation","Java","Agile"]}]. Return only the JSON string.